#version: 3.8
services:
  nginx:
    image: nginx:latest
    container_name: lemp-nginx
    ports:
      - "0:80" #Automatically assigns an available port on the host machine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php
    networks:
      - lemp-network

  php:
    build: ./php
    container_name: lemp-php
    volumes:
      - ./php:/var/www/html
    networks:
      - lemp-network

  mysql:
    image: mariadb:latest
    container_name: lemp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    networks:
      - lemp-network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  lemp-network:
